# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/golang"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/golang:1.18"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: golang
        update-types: ["version-update:semver-major", "version-update:semver-minor"]

  - package-ecosystem: "docker"
    directory: "/node:16"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: node
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "docker"
    directory: "/node:18"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: node
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "docker"
    directory: "/golang:1.19.0"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: golang
        update-types: ["version-update:semver-major", "version-update:semver-minor", "version-update:semver-patch"]

  - package-ecosystem: docker
    directory: /python:3
    schedule:
      interval: daily
    ignore:
      - dependency-name: python
        update-types: [version-update:semver-major]

  - package-ecosystem: docker
    directory: /python:3.10
    schedule:
      interval: daily
    ignore:
      - dependency-name: python
        update-types: [version-update:semver-major, version-update:semver-minor]
